name: MT6737M TWRP Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04 # Откатываемся на более старую Ubuntu, где Python 2 стабильнее

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Tools & Python 2
      run: |
        sudo apt-get update
        # Устанавливаем базу и принудительно добавляем Python 2 для совместимости с Android 6
        sudo apt-get install -y bc bison build-essential curl flex g++ git gnupg gperf libxml2-utils unzip zip python2 python-is-python2

    - name: Download Compatible Repo Tool
      run: |
        # Скачиваем стабильную версию repo прямо в системную директорию
        sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+x /usr/local/bin/repo

    - name: Configure Git
      run: |
        git config --global user.name "Nyxus-dev"
        git config --global user.email "nyxus@example.com"

    - name: Initialize TWRP Source
      run: |
        mkdir twrp && cd twrp
        # Запуск инициализации с явным указанием использовать Python 2
        python2 /usr/local/bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-6.0
        echo "Конфликт версий Python успешно решен!"
