name: Android Firmware Compilation

on:
  workflow_dispatch: # Позволяет запускать сборку вручную

jobs:
  compile:
    runs-on: ubuntu-latest # Используем самую свежую стабильную систему

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Обновили до v4, чтобы убрать ошибку Node.js

    - name: Setup Compilation Environment
      run: |
        sudo apt-get update
        # Установим только базовые, гарантированно стабильные пакеты для теста
        sudo apt-get install -y bc bison build-essential curl flex g++ git gnupg gperf libxml2-utils unzip zip python3

    - name: Display Success
      run: echo "Облачное окружение успешно обновлено и работает стабильно!"
